### PR TITLE
Add Multiply()

### PR DESCRIPTION
**Pull request by s6pepaul**
I tested it on a small scale. I think it is what we want. It sure be fairly efficient, but you know more about this, so feel free to change as you wish.

### CODE REVIEW

**Review by dglazier — COMMENTED** [review]
HI Peter,
  I think this function looks fine, but you may want to consider adding the multiplication to the ImportanceSampling function to save the need to run through all the events again 

MCTree->GetEntry(i);
MCWeights->GetEntryBinarySearch(wID);
mcweight=MCWeights->GetWeight(speciesID);
			FillWeight(wID, 
				ratioHist->GetBinContent( mcweight*ratioHist->GetXaxis()->FindBin(val)));

**Comment by s6pepaul** [comment]
That is true, but at the same time it might be good to have a multiply function.
I was thinking to have this as part of the ImportancaSampling function but decided against it. Of course it is an easy fix.

**Comment by s6pepaul** [comment]
Also shouldn't this

> FillWeight(wID,
> ratioHist->GetBinContent( mcweight*ratioHist->GetXaxis()->FindBin(val)));

be 

FillWeight(wID,
 mcweight*ratioHist->GetBinContent( ratioHist->GetXaxis()->FindBin(val)));

?

**Comment by dglazier** [comment]
Yes I agree the multiply function is good to have. The multiply in ImportanceSampling would just optimise it and probably the weights are never valid without the multiplication in which case you could argue they should not be calculated unmultiplied. I am happy to accept the pull request if you are happy with it.

**Comment by s6pepaul** [comment]
I just made the changes. Feel free to check and then pull.

**Review by dglazier — COMMENTED** [review]
Hi Peter,
  Did you check both methods give the same weighted histogram ? i.e. weight then multiply compared to weight and multiply.
Cheers
Derek

**Comment by s6pepaul** [comment]
I didn't to be honest. I will do it in a few minutes and let you know.

**Comment by s6pepaul** [comment]
Did the test, it is exactly the same.

**Comment by dglazier** [comment]
Perfect.

**Pull request merged**
